[package]
name = "wol-relay"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
wol = "0.3.1"

[profile.release]
strip = true      # Automatically strip symbols from the binary.
lto = true
codegen-units = 1
