[package]
name = "wol-relay"
version = "0.1.0"
edition = "2024"

[dependencies]
wol = "0.3.1"

[profile.release]
strip = true      # Automatically strip symbols from the binary.
lto = true
codegen-units = 1
